### load contracts data
GET http://localhost:5666/gateway/contracts


### load all contract interactions
GET http://localhost:5666/gateway/interactions?contractId=Daj-MNSnH55TDfxqC7v4eq0lKzVIwh98srUaWqyuZtY

### with filtering
http://localhost:5666/gateway/interactions?contractId=Daj-MNSnH55TDfxqC7v4eq0lKzVIwh98srUaWqyuZtY&confirmationStatus=confirmed&from=771000

### with filtering
http://localhost:5666/gateway/interactions?contractId=Daj-MNSnH55TDfxqC7v4eq0lKzVIwh98srUaWqyuZtY&confirmationStatus=corrupted

### ...and paging
http://localhost:5666/gateway/interactions?contractId=Daj-MNSnH55TDfxqC7v4eq0lKzVIwh98srUaWqyuZtY&confirmationStatus=confirmed&page=10

### ...and paging
http://localhost:5666/gateway/interactions?contractId=Daj-MNSnH55TDfxqC7v4eq0lKzVIwh98srUaWqyuZtY&from=771000&confirmationStatus=confirmed&page=10


