#!/bin/sh

# Move to the dev-cli container src
DIR=$PWD
CONTAINER_DIR=/workspace/dev-cli/container/src
cd $CONTAINER_DIR

# Clean
rm -rf /usr/local/ao-module
rm -rf /opt
rm -rf /src
mkdir -p /opt/src

# Copy emcc-lua to bin (Makes it executable via PATH)
cp ./ao-build-module /usr/local/bin/ao-build-module
mkdir -p /usr/local/ao-module
cp -R ./ao_module_lib /usr/local/ao-module/ao_module_lib/

# Copy Container Src
cp -R ./core/. /opt/

cp ./json.lua /opt/src/json.lua
cp ./ao.lua /opt/src/ao.lua

# Copy Rustlib, Node, and Aolibc to /opt
cp -R ./rustlib /opt/rustlib
cp -R ./node /opt/node
cp -R ./aolibc /opt/aolibc

# BUILD WeaveDrive Extension Helper
cd /opt/aolibc
make CC="emcc -s WASM=1 -s MEMORY64=1 -s SUPPORT_LONGJMP=1"

# BUILD Node
cd /opt/node
npm install --omit="dev"
npm link

# Add execute permissions to emcc-lua
chmod +x /usr/local/bin/ao-build-module

# Copy Current Directory TO /src
cp -rf "$DIR" /src



