version: '3.8'

configs:
  su-wallet:
    file: ./services/su/wallet.json
  cu-wallet:
    file: ./services/cu/wallet.json
  mu-wallet:
    file: ./services/mu/wallet.json

volumes:
  su:

services:
  development:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - INSTALL_LUA=${INSTALL_LUA}
        - INSTALL_NODE=${INSTALL_NODE}
        - INSTALL_PYTHON=${INSTALL_PYTHON}
        - INSTALL_EMSDK=${INSTALL_EMSDK}
        - INSTALL_RUST=${INSTALL_RUST}
        - INSTALL_DENO=${INSTALL_DENO}
        - LUA_VERSION=${LUA_VERSION}
        - LUAROCKS_VERSION=${LUAROCKS_VERSION}
        - EMSCRIPTEN_VERSION=${EMSCRIPTEN_VERSION}
        - NODE_VERSION=${NODE_VERSION}
        - PYTHON_VERSION=${PYTHON_VERSION}
        - PYTHON_PIP_VERSION=${PYTHON_PIP_VERSION}

    env_file: .env
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    

  su-db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - su:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: su
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: pg_isready -U su_user -d su_db || exit 1
      start_period: 10s
      start_interval: 1s
    network_mode: host

  su:
    depends_on:
      su-db:
        condition: service_healthy
    build: 
      context: ./services/su
      args:
        - REPO=https://github.com/permaweb/ao.git
        - BRANCH=main
    configs:
      - source: su-wallet
        target: /usr/src/su/wallet.json
    env_file: ./services/su/.env.su
    restart: unless-stopped
    command: sleep infinity
    network_mode: host
    
  cu:
    build: 
      context: ./services/cu
      args:
        - REPO=https://github.com/permaweb/ao.git
        - BRANCH=main
    configs:
      - source: cu-wallet
        target: /usr/src/cu/wallet.json
    env_file: ./services/cu/.env.cu
    restart: unless-stopped
    command: sleep infinity
    network_mode: host

  mu:
    build: 
      context: ./services/mu
      args:
        - REPO=https://github.com/permaweb/ao.git
        - BRANCH=main
    configs:
      - source: mu-wallet
        target: /usr/src/mu/wallet.json
    env_file: ./services/mu/.env.mu
    restart: unless-stopped
    command: sleep infinity
    network_mode: host
