package warp

const (
	TagSequencer               = "Sequencer"
	TagSequencerOwner          = "Sequencer-Owner"
	TagSequencerMillis         = "Sequencer-Mills"
	TagSequencerSortKey        = "Sequencer-Sort-Key"
	TagSequencerLastSortKey    = "Sequencer-Last-Sort-Key"
	TagSequencerTxId           = "Sequencer-Tx-Id"
	TagSequencerBlockHeight    = "Sequencer-Block-Height"
	TagSequencerBlockId        = "Sequencer-Block-Id"
	TagSequencerBlockTimestamp = "Sequencer-Block-Timestamp"
	TagSequencerNonce          = "Sequencer-Nonce"
	TagInitState               = "Init-State"
	TagInitStateTx             = "Init-State-TX"
	TagInteractWrite           = "Interact-Write"
	TagWasmLang                = "Wasm-Lang"
	TagWasmLangVersion         = "Wasm-Lang-Version"
	TagWasmMeta                = "Wasm-Meta"
	TagRequestVrf              = "Request-Vrf"
	TagSignatureType           = "Signature-Type"
	TagWarpTestnet             = "Warp-Testnet"
	TagManifest                = "Contract-Manifest"
	TagNonce                   = "Nonce"
)
