name: Create Release
# Update patch version by default. 
# Use (MAJOR) or (MINOR) in the commit if you want to update corresponding version

on:
    
  workflow_dispatch:
    inputs:
      prerelease:
        type: boolean
        required: false
        default: false     

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Version
        id: version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          short_tags: false

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v0.1.15
        with:
          token: "${{ secrets.RELEASE_TOKEN }}"
          tag_name: ${{ steps.version.outputs.version_tag }}
          prerelease: ${{ inputs.prerelease }}
          name: Release ${{ steps.version.outputs.version_tag }}
          files: |
            docker-compose.yml
            .env.defaults
