name: "cu-production-deploy"

concurrency:
  group: cu-production-deploy-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  deploy-cu:
    runs-on: ubuntu-latest
    env:
      ACCOUNT_ID: 429478883069
      AWS_REGION: us-west-1
      PACKER_FILENAME: cu-testnet.pkr.hcl
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_AO_PROD }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_AO_PROD }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: latest

      - name: Run `packer init`
        id: init
        working-directory: infra/packer
        run: "packer init ./${{ env.PACKER_FILENAME }}"

      - name: Run `packer validate`
        id: validate
        working-directory: infra/packer
        run: "packer validate ./${{ env.PACKER_FILENAME }}"

      - name: Run `packer build`
        id: build
        working-directory: infra/packer
        run: "packer build ./${{ env.PACKER_FILENAME }}"
