name: ⏰ Test & Deploy AO Scheduler Utils

on:
  pull_request:
    branches:
      - main
    paths:
      - "scheduler-utils/**"
  push:
    branches:
      - main
    paths:
      - "scheduler-utils/**"
  
  # Perform a release using a workflow dispatch
  workflow_dispatch:
    inputs:
      version:
        description: "semver version to bump to"
        required: true

defaults:
  run:
    shell: bash

jobs:

  test:
    if: github.event_name != 'workflow_dispatch'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📥 Download deps
        working-directory: scheduler-utils
        run: |
          npm i

      - name: ⚡ Run Tests
        working-directory: scheduler-utils
        run: |
          npm test
        env:
          CI: true

  release:
    # Releases are performed via a workflow dispatch
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    concurrency:
      group: release
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: ⎔ Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"

      - name: 👀 Env
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Git ref:    ${{ github.ref }}"
          echo "GH actor:   ${{ github.actor }}"
          echo "SHA:        ${{ github.sha }}"
          VER=`node --version`; echo "Node ver:   $VER"
          VER=`npm --version`; echo "npm ver:    $VER"

      - name: 🤓 Set Git User
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: ✊ Bump
        id: bump
        uses: hyper63/hyper-ci-bump@v2.0.3
        with:
          bump-to: ${{ github.event.inputs.version }}
          package: scheduler-utils

      - name: ⬆️ Push
        run: |
          git push
          git push --tags

      - name: 📥 Download deps
        working-directory: scheduler-utils
        run: |
          npm i
      
      - name: 🦠 Publish to NPM
        working-directory: scheduler-utils
        run: |
          npm run build
          npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
